- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
    - name: install prerequisite packages
      package: "{{ item }}"
      with_items: 
        - python-psutil

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/cron.yml
    - include: tasks/gnome_settings.yml

