---
- name: Remove "PrtSc" key from the screenshot function
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/screenshot"
    value: "''"
    state: present

- name: Set "PrtSc" key to make a snapshot of a selected screen area
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/area-screenshot-clip"
    value: "'Print'"
    state: present

