- name: Install apt packages
  apt: name={{ item }}
  with_items:
    - htop
    - mc
    - tmux

- name: Install snap packages
  command: snap install {{ item }}
  with_items:
    - spotify
    - tusk
