- name: Install apt packages
  apt: name={{ item }}
  with_items:
    - tlp
    - pinta

- name: Install snap packages
  command: snap install {{ item }}
  with_items:
    - spotify
    - tusk
    - onlyoffice-desktopeditors
    - sublime-text --classic


